"""empty message

Revision ID: 8f4539ad08a0
Revises: 70a4281a376d
Create Date: 2021-08-29 00:39:59.043226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4539ad08a0'
down_revision = '70a4281a376d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    # ### end Alembic commands ###
